### ISSUE TITLE
[FEATURE] Allow nolock mount option

### ISSUE THREAD

**Issue by gladdiologist** [cloudfoundry/smbbroker#2]
Hi,

It would be nice to allow the "nolock" mount flags.
I would be happy to make a pull request but it seems this option also requires the addition of this feature on the drivers...

**Comment by julian-hj** [comment]
Hi @gladdiologist can you give us a bit more detail about why you want the nolock option?  For example is it because you don't want file locking over the network?  Or you don't want to rely on the rpc netbind service and port 111, but you cannot use NFSv4 for some reason?

**Comment by gladdiologist** [comment]
hi @julian-hj, 
I'm using a task for running [tippecanoe](https://github.com/mapbox/tippecanoe) over an azure file share as a service volume. This program is designed to build vector tilesets in a compressed format (mbtiles) that relies on sqlite. When joining multiple mbtiles files in one, the process crash with a "database is locked". I tried to disable multithreading but this was unsuccessful.
In my case, mouting the volume with nolock flag is a pretty good workaround. That's why i would appreciate this option to be available in mount options, and only use it carefully while waiting a [fix](https://github.com/mapbox/tippecanoe/issues/805#issue-507070568) for a tool that may not well behave with network share.

**Comment by julian-hj** [comment]
Hi @gladdiologist,

Hmm, this doesn't seem like a use case we probably want to officially support. Turning off locking because someone else has a locking bug doesn't feel particularly safe or advisable to me.

Having said that, you can certainly build the bosh release yourself with the requisite changes to allow `nolock` in your services.  I replied to your slack query with the two code locations where we are hard coding allowed options in the driver and broker.  If you change those two strings, and then rebuild the  bosh release and upload it & redeploy, you should be OK to run in the dangerous state you are requesting.

I'm going to go ahead and close this issue, but please feel free to re-open it or open a new one if you require further assistance.

Cheers,
-Julian

**Comment by gladdiologist** [comment]
Thx a lot Julian, tippecanoe team is going to investigate it. Cheers!
